import type { ProfileData } from '../types/profile'

export const profileData: ProfileData = {
  name: 'Snehalkumar Joshi',
  title: 'Senior Software Engineer | Distributed Systems | AI Search',
  email: 'snehaljoshi09@hotmail.com',
  summary: [
    'Senior Software Engineer specializing in scalable backend systems, distributed architectures, and AI-powered search platforms.',
    'Strong expertise in high-throughput microservices, event-driven systems, Retrieval-Augmented Generation (RAG), and hybrid semantic search.',
    'Designed and operated production systems processing 4,000+ RPM at 99.70% SLO on AWS infrastructure.',
    'Track record of building resilient, decoupled architectures at enterprise scale for large SaaS platforms.',
  ],
  skills: {
    'AI & Search Systems': [
      'RAG (Retrieval-Augmented Generation)',
      'Hybrid Search (pgvector + keyword)',
      'Embeddings',
      'OpenAI APIs',
      'LangChain',
      'Semantic Retrieval',
    ],
    'Distributed Systems': [
      'Event-Driven Architecture',
      'Kafka',
      'Microservices',
      'AWS Step Functions',
      'Stateless Service Design',
      'Horizontal Scalability',
    ],
    'Cloud Architecture': [
      'AWS Lambda',
      'API Gateway',
      'ECS',
      'SQS / SNS',
      'DynamoDB',
      'S3',
      'AWS CloudFormation',
      'AWS Keyspaces',
    ],
    'Backend Engineering': [
      'TypeScript',
      'Node.js',
      'Python',
      'Java',
      'Spring Boot',
      'PostgreSQL',
      'MySQL',
      'Oracle',
      'REST APIs',
    ],
    'Observability & DevOps': [
      'Datadog',
      'AWS CloudWatch',
      'SLO Ownership',
      'CI/CD Optimization',
      'Alerting & Monitoring',
    ],
    'Frontend': [
      'React',
      'Vite',
      'Storybook',
      'HTML5 / CSS3',
    ],
  },
  experience: [
    {
      company: 'The Washington Post',
      role: 'Senior Software Engineer',
      period: 'Nov 2022 – Present',
      bullets: [
        'Architected backend platforms powering a large-scale SaaS CMS ecosystem serving editorial and publishing workflows.',
        'Designed and implemented RAG-based semantic search using PostgreSQL + pgvector with hybrid (vector + keyword) retrieval across 10K+ content entities.',
        'Architected centralized reference graph service (depth-2 modeling) consumed by multiple downstream services to enhance content relationship intelligence.',
        'Designed and developed a lightweight rule and validation engine positioned before content editor and ingestion pipelines.',
        'Re-architected comments and suggestions into reusable, stateless service modules enabling horizontal scaling and simplified service integration.',
        'Implemented Kafka-based event-driven architecture to decouple services and enable independent scaling.',
        'Engineered microservices processing 4,000+ requests per minute while maintaining 99.70% SLO.',
        'Reduced onboarding workflows from hours to minutes through distributed system redesign.',
        'Optimized CI/CD pipelines reducing deployment time from ~40 minutes to under 15 minutes.',
        'Integrated LLM-based answer generation layered on semantic retrieval pipelines using OpenAI APIs and LangChain.',
        'Implemented monitoring, alerting, and SLO tracking using Datadog and AWS CloudWatch.',
      ],
    },
    {
      company: 'JRI-America (SMBC)',
      role: 'Software Engineer',
      period: 'Mar 2022 – Nov 2022',
      bullets: [
        'Developed data governance workflows and UI components for enterprise data quality systems.',
        'Built frontend interfaces using JavaScript libraries and supported backend REST services in Java.',
        'Collaborated with business stakeholders to translate regulatory requirements into scalable workflows.',
      ],
    },
    {
      company: 'Freedom Mortgage',
      role: 'Software Engineer / BPM Developer',
      period: 'Jun 2016 – Mar 2022',
      bullets: [
        'Built backend microservices using Java, Spring, and Spring Boot.',
        'Implemented AWS Step Functions for enterprise workflow automation.',
        'Developed OCR automation solutions using AWS Textract and Tesseract.',
        'Built UI applications using IBM BAW integrated with React components.',
        'Integrated RPA solutions to modernize legacy enterprise workflows.',
      ],
    },
  ],
  education: [
    {
      degree: 'Master of Science in Computer Science',
      school: 'New York Institute of Technology',
      period: 'Dec 2015',
    },
    {
      degree: 'Bachelor of Computer Engineering',
      school: 'Gujarat Technological University',
      period: '2013',
    },
  ],
}
