import type { ProfileData } from '../types/profile'

export const profileData: ProfileData = {
  name: 'Snehalkumar Joshi',
  title: 'Senior Software Engineer | Distributed Systems | AI Search',
  email: 'snehaljoshi09@hotmail.com',
  summary: [
    'Senior Software Engineer with 9+ years of experience designing and delivering scalable, high-performance systems across the full stack.',
    'Experienced in distributed architectures, event-driven systems, cloud-native services, and AI-powered features.',
    'Consistent track record of owning complex problems end-to-end, shipping reliable software at scale, and driving measurable improvements in system performance and developer productivity.',
  ],
  skills: {
    'AI & Search Systems': [
      'RAG (Retrieval-Augmented Generation)',
      'Hybrid Search (pgvector + keyword)',
      'Embeddings',
      'OpenAI APIs',
      'LangChain',
      'Semantic Retrieval',
    ],
    'Distributed Systems': [
      'Event-Driven Architecture',
      'Kafka',
      'Microservices',
      'AWS Step Functions',
      'Stateless Service Design',
      'Horizontal Scalability',
    ],
    'Cloud Architecture': [
      'AWS Lambda',
      'API Gateway',
      'ECS / Fargate',
      'SQS / SNS',
      'DynamoDB',
      'S3',
      'AWS CloudFormation',
      'AWS Keyspaces',
      'Docker',
      'Terraform',
    ],
    'Backend Engineering': [
      'TypeScript',
      'Node.js',
      'Python',
      'Java',
      'Go',
      'SQL',
      'Spring Boot',
      'PostgreSQL',
      'MySQL',
      'Oracle',
      'REST APIs',
    ],
    'Observability & DevOps': [
      'Datadog',
      'AWS CloudWatch',
      'SLO Ownership',
      'CI/CD Optimization',
      'Alerting & Monitoring',
    ],
    'Frontend': [
      'React',
      'Vite',
      'HTML5 / CSS3',
    ],
  },
  experience: [
    {
      company: 'The Washington Post',
      role: 'Senior Software Engineer',
      period: 'Nov 2022 – Present',
      bullets: [
        'Architected backend platforms powering a large-scale SaaS CMS ecosystem serving 50+ editorial clients.',
        'Designed and implemented RAG-based semantic search using PostgreSQL + pgvector with hybrid (vector + keyword) retrieval across 10K+ content entities, reducing end-to-end searchable time to under 30 seconds.',
        'Architected centralized reference graph service (depth-2 modeling) used by 3–4 downstream services, reducing cross-service query latency by 30%.',
        'Designed and developed lightweight rule and validation engine performing data ingestion checks at 5,000+ req/min, reducing invalid content errors and enabling per-client personalization.',
        'Re-architected comments and suggestions into reusable, stateless service modules enabling horizontal scaling and simplifying service integration.',
        'Implemented Kafka-based event-driven architecture to decouple 4+ services, eliminating synchronous bottlenecks and enabling independent scaling.',
        'Engineered and maintained microservices processing 4,000+ requests per minute at 99.70% SLO with zero major service outages over 12+ months.',
        'Reduced client onboarding workflows from 4+ hours to under 10 minutes through distributed system redesign.',
        'Optimized CI/CD pipelines reducing deployment time from ~40 minutes to under 15 minutes across 5+ services.',
        'Designed and shipped LLM-based natural language querying over structured content as a net-new product capability, layered on existing RAG retrieval infrastructure.',
        'Implemented comprehensive monitoring, alerting, and SLO tracking using Datadog and AWS CloudWatch, supporting 12+ months of uninterrupted production stability.',
      ],
    },
    {
      company: 'JRI-America (SMBC)',
      role: 'Software Engineer',
      period: 'Mar 2022 – Nov 2022',
      bullets: [
        'Leveraged workflow automation to improve a Data Quality Management pipeline by 20–25%, reducing data defects and improving downstream data reliability.',
        'Built and delivered a data migration pipeline for transitioning legacy datasets into modernized enterprise systems, enabling seamless workflow continuity.',
        'Built frontend interfaces using React/JavaScript and supported backend REST services in Java across enterprise data governance systems.',
      ],
    },
    {
      company: 'Freedom Mortgage',
      role: 'Software Engineer / BPM Developer',
      period: 'Jun 2016 – Mar 2022',
      bullets: [
        'Built backend microservices using Java, Spring Boot, and AWS Step Functions for enterprise workflow automation supporting 500K+ annual loan applications.',
        'Led a team of 3 engineers to architect and deliver an in-house Data Extraction Pipeline using AWS Textract and Tesseract, reducing per-page processing cost from $1.00 (vendor) to $0.35 in-house — delivering high ROI at scale across 10+ document types.',
        'Modernized legacy enterprise workflows by integrating RPA solutions and building React UI applications on IBM BAW, eliminating 3 legacy systems.',
        'Designed RESTful APIs and database schemas (Oracle, MySQL) supporting high-throughput mortgage processing pipelines.',
      ],
    },
  ],
  education: [
    {
      degree: 'Master of Science in Computer Science',
      school: 'New York Institute of Technology',
      period: 'Dec 2015',
    },
    {
      degree: 'Bachelor of Computer Engineering',
      school: 'Gujarat Technological University',
      period: 'May 2013',
    },
  ],
}
